#!/home/freeman/anaconda3/envs/aidds/bin/python
import os

from aidds import run_args
from aidds.sys import config as cfg

args = run_args()
exec_str = 'python '
if args.cleaning:
    exec_str += './cleaning/run.py'
elif args.serving:
    exec_str += './serving/run.py '
    if args.debug or cfg.sys.cond.debug_mode:
        exec_str += '-d '
    if args.port == 0:
        args.port = cfg.sys.web.port
    exec_str += f'--port {args.port}'
else:
    exec_str += './modeling/run.py'

os.system(exec_str)